name: CI - Run Pytest

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install pytest

      - name: Run pytest
        run: |
          pytest -vv > pytest-log.txt || true

      - name: Upload pytest logs
        uses: actions/upload-artifact@v4
        with:
          name: pytest-log
          path: pytest-log.txt
